db:
  host: 'localhost'
  username: 'postgres'
  password: 'postgres'
  synchronize: true
  port: 5432
  database: 'taskmanagement'

jwt:
  secret: '@this_7smY!SecRe7ForJwT)auTh!'
  expiresIn: 86400 # One day in seconds
